### ISSUE TITLE
variableInspector makes entries in IPython output history cache

### ISSUE THREAD

**Issue by maresb** [lckr/jupyterlab-variableInspector#106]
I just installed the latest version from GitHub into JupyterLab 1.0.2, and I see this strange behavior.  It's easier to show than to explain.  Pay attention to the cell numbers.  They start from either 2 or 3, and they increment by 2 after each cell evaluation:

![Peek 2019-07-23 19-23](https://user-images.githubusercontent.com/15216687/61733594-701eda00-ad80-11e9-9674-b94d6303bf41.gif)

```
_1 = []
_2 = []
```
Apparently the variableInspector output is being assigned to its own underscore-number variable after each cell evaluation.

**Comment by lckr** [comment]
Fix coming soon.

**Comment by lckr** [comment]
The behavior of the counter should be fixed in #107.

Regarding the issue with populating the kernel with `_1` et al. I investigated a little bit. It seems like this is standard behavior in jupyterlab and happens even without the variable inspector installed and for versions prior to jupyterlab 1.0.0. (Usually the variables then are named `_i1` etc.
