### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by h4gen** [lckr/jupyterlab-variableInspector#31]
When I start a console from a notebook with activated variable inspector, every change of a variable causes that the whole content of the variable explorer ist printed to the console. This leads to a practically unusable console, as it is just spammed with the the whole variable inspector content over and over again.

**Comment by lckr** [comment]
Hey, thanks for your report. I will look into it.

**Comment by lckr** [comment]
I took a look into this over the weekend. We are currently using a new handler for both the notebook and the connected console, this results in two inspection requests per `execute request`. 
I implemented a fix for that in an not yet uploaded branch. Sadly this does not fix the described behaviour. I suspect that consoles connected to existing sessions do not respect the `store_history : false` setting of the execute request that we send to the kernel.

I will take a closer look on this in the next days

**Comment by h4gen** [comment]
@lckr thanks a lot for the effort! Without this flaw the variable inspector is pure gold for me :)

**Comment by lckr** [comment]
Hey,
According to the documentation [here](http://jupyterlab.github.io/jupyterlab/classes/_console_src_widget_.codeconsole.html#showallactivity), there should be a possibility to disable this console echo. Even though the [related PR](https://github.com/jupyterlab/jupyterlab/pull/4503) has been merged some time ago, I wasn't able to use this accessor, since it is not available in the current version of the '@jupyterlab/console' module on npm yet. 

We will need to update our dependencies once available.

**Comment by lckr** [comment]
This will be fixed  with #35. Please note that you need to upgrade to the jupyterlab version **0.33**. AFAIK you need to build it from source at the moment, since it is not on conda yet.
